#%RAML 1.0
title: api-development HRMatches API
version: v0.1
baseUri: http://api-development.hrmatches.com
traits:
  token_required:
    queryParameters:
      token:
        type: string
        description: The server-generated token issued to the user after a successful login
        example: E27B40D6-6C62-6D46-AC144BDF0E9A1D68
        required: true
        minLength: 35
        maxLength: 35
  token_optional:
    queryParameters:
      token:
        type: string
        description: The server-generated token issued to the user after a successful login
        example: E27B40D6-6C62-6D46-AC144BDF0E9A1D68
        required: false
        minLength: 35
        maxLength: 35
  response_delete_ok:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                "message": "DELETE_OK"
                }
  response_post_ok:
    responses:
      200:
        body:
          application/json:
            example: |
              {
              "message": "POST_OK"
              }
  response_put_ok:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                "message": "PUT_OK"
                }

  response_delete_nok:
      responses:
        3xx:
        4xx:
        5xx:
          body:
            application/json:
              example: |
                {
                "message": "DELETE_NOK"
                }
  response_get_nok:
    responses:
      3xx:
      4xx:
      5xx:
        body:
          application/json:
            example: |
              {
              "message": "GET_NOK"
              }
  response_post_nok:
      responses:
        3xx:
        4xx:
        5xx:
          body:
            application/json:
              example: |
                {
                "message": "POST_NOK"
                }
  response_put_nok:
      responses:
        3xx:
        4xx:
        5xx:
          body:
            application/json:
              example: |
                {
                "message": "PUT_NOK"
                }


#################
# API Endpoints
#################

# validate_token:

/validate_token:
  /{token}:
    get:
      #description: validate a users token generated by server after succesful authentication
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                tokenIsValid: boolean
              example:
                value: {
                    "tokenIsValid": true
                  }
        3xx:
        4xx:
        5xx:
          body:
            application/json:
              type: object
              properties:
                tokenIsValid: boolean
              example: |
                {
                    "tokenIsValid": false
                }

# actionItem

/actionItem:
  is: [ token_optional ]
  get:
    is: [response_get_nok]
    responses:
      200:
        body:
          application/json:
            description : an unordered lists of actionitems
            type: array
            items:
              type: object
              properties:
                itemId:
                  type: string
                  description: the item id
                itemLabel:
                  type: string
                  description: the item human readable label
                actionUrl:
                  type: string
                  description: the action (a http request) to execute when chosen
                actionItemIconName:
                  type: string
                  description: name of actionitem
            example:
              [{
                "itemId": "0DDCBBD4-6C62-6D46-AC1475645F5FUG4D",
                "itemLabel": "Dashboard",
                "actionUrl": "/dashboard",
                "actionItemIconName": "dashboard_icon"
              },{
                "itemId": "0DDCB5D4-6C62-6D46-AC1475645F55UG4D",
                "itemLabel": "Kandidaten",
                "actionUrl": "/candidates",
                "actionItemIconName": "candidates_icon"
              },{
                "itemId": "0DDCBBD4-6C62-6R46-AC1475645F55UG4D",
                "itemLabel": "Vacatures",
                "actionUrl": "/jobs",
                "actionItemIconName": "jobs_icon"
              },{
                "itemId": "0DDCBBD4-6C62-6D46-AC1465645F55UG4D",
                "itemLabel": "Statistieken",
                "actionUrl": "/statistics",
                "actionItemIconName": "statistics_icon"
              },{
                "itemId": "0DDCBBD4-6C62-6D46-AC1475645F74FF4D",
                "itemLabel": "Actief",
                "actionUrl": "/candidates/mostActive",
                "actionItemIconName": "dashboard_icon"
              },{
                "itemId": "0DDCBBD4-6C62-6D46-AC1575645F74FG4D",
                "itemLabel": "Recent",
                "actionUrl": "/candidates/recent",
                "actionItemIconName": "recentCandidates_icon"
              }]
  delete:
    is: [response_delete_ok,response_delete_nok]
    description: delete the specified actionMenuItem by id
    queryParameters:
      body:
        type: string
        required: true
  post:
    is: [response_post_ok,response_post_nok]
    description: create a new actionMenuItem
    body:
      application/json:
        type: object
        properties:
          itemId:
            type: string
            description: the item id
          itemLabel:
            type: string
            description: the item human readable label
          actionUrl:
            type: string
            description: the action (a http request) to execute when chosen
          actionItemIconName:
            type: string
            description: name of actionitem
        example: |
          {
            "itemId": "0DDCBBD4-6C62-6D46-AC1575645F74FG4D",
            "itemLabel": "Recent",
            "actionUrl": "/candidates/recent",
            "actionItemIconName": "recentCandidates_icon"
          }
  put:
    is: [response_put_ok,response_put_nok]
    description: edit the resource
    body:
      application/json:
        type: object
        properties:
          itemId:
            type: string
            description: the item id
          itemLabel:
            type: string
            description: the item human readable label
          actionUrl:
            type: string
            description: the action (a http request) to execute when chosen
          actionItemIconName:
            type: string
            description: name of actionitem
        example:
          {
            "itemId": "0DDCBBD4-6C62-6D46-AC1575645F74FG4D",
            "itemLabel": "Recent",
            "actionUrl": "/candidates/recent",
            "actionItemIconName": "recentCandidates_icon"
          }

# menu

/menu:
  is: [ token_optional,response_get_nok ]
  get:
    description: retrieve menus for application
    queryParameters:
      depth:
        type: number
        default: 0
        description: how many levels should the menu at maximum contain? 0 = no submenus, 1 = max 1 submenu etc
        example: 2
        required: false
      node:
        type: string
        default: ""
        description: What is the menu's parent?
        example: "0DDCBBD4-6C62-6D46-AC1475645F74FG4D"
        required: true
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: object
              properties:
                itemId:
                  type: string
                itemLabel:
                  type: string
                parent:
                  type: string
                orderBy:
                  description: |
                    possible values are:
                    'natural' [type: string] - same order as in db table,
                    'alphabetic' [type: string] - in ascending order
                    'custom' [type: integer]- a user provided integer value)
                  type: string
                sortOrder:
                  description: the user-defined sort order of a menu item
                  type: integer
                  required: false
                type:
                  description: |
                    a menu item can be single, separator
                    (a line separating singleitems) or
                    compound (containing a submenu)
                  type: string
                actionUrl:
                  type: string
                menuItemIconName:
                  type: string
                  description: name of menuitem
            example:
                [{
                  "itemId": "0DDCBBD4-6C62-6D46-AC1475645F74FG4D",
                  "itemLabel": "Dashboard",
                  "parent": "",
                  "orderBy": "natural",
                  "type": "singleItem",
                  "actionUrl": "/dashboard",
                  "menuItemIconName": "dashboard_icon"
                },{
                  "itemId": "0DDCBBD4-6C62-6D46-AC1475645F74FF4D",
                  "itemLabel": "Vacatures",
                  "parent":"",
                  "orderBy": "natural",
                  "type":"singleItem",
                  "actionUrl": "/jobs",
                  "menuItemIconName": "jobs_icon"
                },{
                  "itemId": "0DDCBBD4-6C62-6D46-AC1475645F74FG4D",
                  "itemLabel": "",
                  "parent": "",
                  "orderBy": "natural",
                  "type": "itemSeparator",
                  "actionUrl": "",
                  "menuItemIconName": ""
                }]
  post:
    is: [response_post_ok,response_post_nok]
    body:
      application/json:
        type: object
        properties:
          itemId:
            type: string
          itemLabel:
            type: string
          parent:
            type: string
          orderBy:
            description: |
              possible values are:
              'natural' [type: string] - same order as in db table,
              'alphabetic' [type: string] - in ascending order
              'custom' [type: integer]- a user provided integer value)
            type: string
          sortOrder:
            description: the user-defined sort order of a menu item
            type: integer
            required: false
          type:
            description: |
              a menu item can be single, separator
              (a line separating singleitems) or
              compound (containing a submenu)
            type: string
          actionUrl:
            type: string
          menuItemIconName:
            type: string
            description: name of menuitem
        example:
          {
            "itemId": "0DDCBBD4-6C62-6D46-AC1475645F74FG4D",
            "itemLabel": "",
            "parent": "",
            "orderBy": "natural",
            "type": "itemSeparator",
            "actionUrl": "",
            "menuItemIconName": ""
          }
  put:
    is: [response_put_ok,response_put_nok]
    body:
      application/json:
        type: object
        properties:
          itemId:
            type: string
          itemLabel:
            type: string
          parent:
            type: string
          orderBy:
            description: |
              possible values are:
              'natural' [type: string] - same order as in db table,
              'alphabetic' [type: string] - in ascending order
              'custom' [type: integer]- a user provided integer value)
            type: string
          sortOrder:
            description: the user-defined sort order of a menu item
            type: integer
            required: false
          type:
            description: |
              a menu item can be single, separator
              (a line separating singleitems) or
              compound (containing a submenu)
            type: string
          actionUrl:
            type: string
          menuItemIconName:
            type: string
            description: name of menuitem
        example:
          {
            "itemId": "",
            "itemLabel": "",
            "parent": "",
            "orderBy": "natural",
            "type": "itemSeparator",
            "actionUrl": "",
            "menuItemIconName": ""
          }

  delete:
    is: [response_delete_ok,response_delete_nok]
    queryParameters:
      id:
        type: string
        required: true
  /{node}:
    description: Where in the menu context tree does this menu appear? value "" means there is no parent menu, any other value implies this is a submenu.
    get:
      responses:
        200:
          body:
            Application/json:
              type: object
              properties:
                itemId:
                  type: string
                itemLabel:
                  type: string
                parent:
                  type: string
                orderBy:
                  type: string
                type:
                  type: string
                actionUrl:
                  type: string
                menuItemIconName:
                  type: string
                  description: name of menuitem
              example:
                {
                  "itemId": "0DDCBBD4-6C62-6D46-AC1475645F74FG4D",
                  "itemLabel": "Dashboard",
                  "parent": "",
                  "orderBy": "natural",
                  "type": "singleItem",
                  "actionUrl": "/dashboard",
                  "menuItemIconName": "dashboard_icon"
                }

#validate_secretkey

/validate_secretkey:
  is: [response_post_ok]
  post:
    body:
      application/json:
        properties:
          secretkey:
            type: string
            description: Secret key validates the user who requested resetpassword
            example: E27B40D6-6C62-6D46-AC144BDF0E9A1D68
            required: true
            minLength: 35
            maxLength: 35

# users

/users:
  is: [ token_required]
  get:
    is: [ token_required,response_get_nok]
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: object
              properties:
                firstName: string
                infix: string
                id: string
                emailaddress: string
                lastName: string
            example:
              [{
                "firstName": "John",
                "infix": "",
                "id": "605a0302-cc33-449a-ac50-5ef26e3e3330",
                "emailaddress": "john@doe.nl",
                "lastName": "Doe"
                },{
                "firstName": "May",
                "infix": "",
                "id": "605a0302-cd33-449a-aj50-5ef26e3e5230",
                "emailaddress": "may@doe.nl",
                "lastName": "Doe"
               },{
               "firstName": "Will",
               "infix": "",
               "id": "605a0312-ch33-449a-ac50-5efd6e3e3330",
               "emailaddress": "will@doe.nl",
               "lastName": "Doe"
               },{
               "firstName": "Cat",
               "infix": "",
               "id": "605a0302-ck33-449a-ac50-5ef26e3e5230",
               "emailaddress": "cat@doe.nl",
               "lastName": "Doe"
               }
              ]
  post:
    is: [response_post_ok,response_post_nok]
    body:
      application/json:
        properties:
          person:
            type: object
            properties:
              firstName: string
              infix: string
              id: string
              emailaddress: string
              lastName: string
          token:
            type: string
            required: true
        example: |
          {
           "person": {
             "firstName": "John",
             "infix": "",
             "id": "605a0302-cc33-449a-ac50-5ef26e3e3330",
              "emailaddress": "john@doe.nl",
              "lastName": "Doe"
              },
           "token": "42E2BC51-6C62-6D46-AC1457446EC4C737"
          }
  delete:
   is: [response_delete_ok,response_delete_nok]
   queryParameters:
      teamId:
        required: false
      personId:
        required: true

  /{personId}:
    is: [ token_required ]
    get:
      is: [response_get_nok]
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                firstName: string
                infix: string
                id: string
                emailaddress: string
                lastName: string
              example:
                {
                  "firstName": "John",
                  "infix": "",
                  "id": "605a0302-cc33-449a-ac50-5ef26e3e3330",
                  "emailaddress": "john@doe.nl",
                  "lastName": "Doe"
                  }
    post:
      is: [response_post_ok,response_post_nok]
      body:
        application/json:
          properties:
            person:
              type: object
              properties:
                firstName: string
                infix: string
                id: string
                emailaddress: string
                lastName: string
            token:
              type: string
              required: true
          example: |
            {
             "person": {
               "firstName": "John",
               "infix": "",
               "id": "605a0302-cc33-449a-ac50-5ef26e3e3330",
                "emailaddress": "john@doe.nl",
                "lastName": "Doe"
                },
             "token": "42E2BC51-6C62-6D46-AC1457446EC4C737"
            }
    delete:
      is: [response_delete_ok,response_delete_nok]
      body:
        application/json:
          type: object
          properties:
            teamId:
              required: false
              type: string
            personId:
              required: true
              type: string
          example: |
            {
              "teamId": "605a0302-cc33-449a-ed50-5ef33e3e3330",
              "personId": "605a0302-cc23-449a-cc50-5ef33e3e3330"
            }
# translation

/translation:
  is: [ token_optional,
    response_get_nok ] # this covers all responses except GET 200
  get:
    queryParameters:
      language:
        required: false
      languageKey:
        required: false
    responses:
      200:
        body:
          application/json:
            type: object
            facets:
              configuration:
                properties:
                  columns:
                    type: object
                    properties:
                      visible: boolean
                      columnName: boolean
                      header_visible: boolean
                      header_text: boolean
                      cell_editable: boolean
                  row_editable:
                      type: boolean
                  pagination:
                    type: object
                    facets:
                      enable: boolean
                      itemsPerPage: integer
                      maxSize: integer
              data:
                type: array
                facets:
                  objects:
                    properties:
                      id: string
                examples:
                  array: |
                    {
                    "configuration": {
                    "columns": [
                        {
                           "visible": true,
                           "columnName": "id",
                           "header_visible": true,
                           "header_text": "id",
                           "cell_editable": false
                        },
                        {
                           "visible": true,
                           "columnName": "DisplayName",
                           "header_visible": true,
                           "header_text": "DisplayName",
                           "cell_editable": false
                        },
                        {
                           "visible": true,
                           "columnName": "displayName",
                           "header_visible": true,
                           "header_text": "displayName",
                           "cell_editable": false
                        }
                     ],
                      "row_editable": true,
                      "pagination": {
                          "enable": true,
                          "itemsPerPage": 15,
                          "maxSize": 10
                        }
                      },
                  "data": [
                     {
                        "DisplayName": "Over kandidaat",
                        "id": "APPLICANT_ABOUT_CANDIDATE"
                     },
                     {
                        "DisplayName": "Activiteiten",
                        "id": "APPLICANT_ACTIVITY"
                     },
                     {
                        "DisplayName": "Notitie",
                        "id": "APPLICANT_ADD_NOTE"
                     },
                     {
                        "DisplayName": "Taak",
                        "id": "APPLICANT_ADD_TASK"
                     }]
# trackdata

/trackdata:
  post:
    body:
      application/json:
        properties:
          trackingData:
            required: true
            type: object
            description: A collection of browser object properties to identify the client
            properties:
              token: string
              state: string
              protocol: string
              hostname: string
              href: string
              appVersion: string
              language: string
              platform: string
              userAgent: string
              screenSize: string
              colorDepth: string
        example: |
          {
            "trackingData": {
              "token": "0DDCBBD4-6C62-6D46-AC1475645F74A49D",
              "state": "settings.account.person",
              "protocol": "http:",
              "hostname": "ojt.hrmatches.com",
              "href": "http://ojt.hrmatches.com/#/settings/account",
              "appVersion": "5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36",
              "language": "en-US",
              "platform": "Win32",
              "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36",
              "screenSize": "1280*1024",
              "colorDepth": "24"
            }
          }

# teams

/teams:
  is: [ token_required ]
  get:
    is: [response_get_nok]
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: object
              properties:
                displayName: string
                id: string
                domainOwnerId: string
            example:
              [{
                "displayName": "Logistics",
                "id": "ae6a0c10-682f-44776-77355-03cc6u9bdd7",
                "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2"
                },{
                "displayName": "HR",
                "id": "b367ed11-7d94-4353-a8c4-489160b747c3",
                "domainOwnerId": "83569745-1855-4f88-9c09-7caf9ea6c6b2"
                },{
                "displayName": "Demo",
                "id": "4c387h21-01b8-448e-adff-1b158440d3c8",
                "domainOwnerId": "83399755-1855-4f68-9c79-7c9f99h6a6b2"
              }]
  post:
    body:
      application/json:

        type: object
        properties:
          teams:
            required: true
            type: array
            items:
              type: object
              properties:
                id: string
                displayName: string
                domainOwnerId: string
                members:
                  type: array
                  items:
                    type: object
                    properties:
                      firstName: string
                      infix: string
                      roleId: integer
                      lastName: string
                      personId: string
        example: |
          {
            "teams": [{
              "id": ""
              ,"displayName": "Team HR"
              ,"domainOwnerId": ""
              ,"members": [{
                "firstName": "Jean",
                "infix": "",
                "roleId": 20,
                "lastName": "Pieter",
                "personId": "fbabcb4b-bf44-4ce3-871c-118c1c5d322a"
              }]
            }]
          }
  put:
    body:
      application/json:
        type: object
        properties:
          teams:
            required: true
            type: array
            items:
              type: object
              properties:
                id: string
                displayName: string
                domainOwnerId: string
                members:
                  type: array
                  items:
                    type: object
                    properties:
                      firstName: string
                      infix: string
                      roleId: integer
                      lastName: string
                      personId: string
        example:
          {
            "teams": [{
              "id": ""
              ,"displayName": "Team HR"
              ,"domainOwnerId": ""
              ,"members": [{
                "firstName": "Jean",
                "infix": "",
                "roleId": 20,
                "lastName": "Pieter",
                "personId": "fbabcb4b-bf44-4ce3-871c-118c1c5d322a"
              }]
            }]
          }
  delete:
    queryParameters:
      teamId:
        required: true
  /{teamId}:
    get:
      responses:
        200:
          body:
            application/json:
              type: object
              example:
                {
                  "members": [],
                  "displayName": "Demo",
                  "id": "4c387h21-01b8-448e-adff-1b158440d3c8",
                  "domainOwnerId": "83399755-1855-4f68-9c79-7c9f99h6a6b2"
                }

/role:
  is: [ token_required ]
  get:
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: object
              properties:
                id: integer
                systemName: string
                displayName: string
                PERMISSIONS:
                  type: array
                  items:
                    type: object
                    properties:
                      displayName: string
                      id: integer
                      permissionName: string
            example:
              [{
                "displayName": "Manager",
                "PERMISSIONS": [
                   {
                      "displayName": "SEND MESSAGES",
                      "id": 15,
                      "permissionName": "SEND MESSAGES"
                   },
                   {
                      "displayName": "EDIT JOB STATUS",
                      "id": 5,
                      "permissionName": "EDIT JOB STATUS"
                   },
                   {
                      "displayName": "EDIT JOB",
                      "id": 4,
                      "permissionName": "EDIT JOB"
                   }],
                "id": 29,
                "systemName": "Manager"
             },{
                "displayName": "Beoordelaar",
                "PERMISSIONS": [
                   {
                      "displayName": "VIEW JOBS",
                      "id": 21,
                      "permissionName": "VIEW JOBS"
                   }
                ],
                "id": 30,
                "systemName": "Beoordelaar"
             }]
  post:
    body:
      application/json:
        type: array
        facets:
          objects:
            properties:
              id: integer
              systemName: string
              displayName: string
              PERMISSIONS:
                type: array
                items:
                  type: object
                  properties:
                    displayName: string
                    id: integer
                    permissionName: string
        example:
          [{
            "displayName": "Manager",
            "PERMISSIONS": [
               {
                  "displayName": "SEND MESSAGES",
                  "id": 15,
                  "permissionName": "SEND MESSAGES"
               },{
                  "displayName": "EDIT JOB STATUS",
                  "id": 5,
                  "permissionName": "EDIT JOB STATUS"
               },{
                  "displayName": "EDIT JOB",
                  "id": 4,
                  "permissionName": "EDIT JOB"
               },{
                  "displayName": "MATCHING",
                  "id": 17,
                  "permissionName": "MATCHING"
               },{
                  "displayName": "ADMINISTRATION",
                  "id": 12,
                  "permissionName": "ADMINISTRATION"
               },{
                  "displayName": "BULK ACTION",
                  "id": 32,
                  "permissionName": "BULK ACTION"
               },{
                  "displayName": "USERMANAGEMENT",
                  "id": 11,
                  "permissionName": "USERMANAGEMENT"
               },{
                  "displayName": "CREATE JOB",
                  "id": 3,
                  "permissionName": "CREATE JOB"
               },{
                  "displayName": "ACCOUNT",
                  "id": 16,
                  "permissionName": "ACCOUNT"
               },{
                  "displayName": "ACTIVITYSTREAM",
                  "id": 8,
                  "permissionName": "ACTIVITYSTREAM"
               },{
                  "displayName": "CANDIDATES",
                  "id": 7,
                  "permissionName": "CANDIDATES"
               },{
                  "displayName": "STATISTICS",
                  "id": 6,
                  "permissionName": "STATISTICS"
               },{
                  "displayName": "TAGMANAGEMENT",
                  "id": 13,
                  "permissionName": "TAGMANAGEMENT"
               },{
                  "displayName": "PUBLISH JOB",
                  "id": 14,
                  "permissionName": "PUBLISH JOB"
               }],
            "id": 0,
            "systemName": "Manager"
            }]
  put:
    body:
      application/json:
        type: array
        items:
          type: object
          properties:
            id: integer
            systemName: string
            displayName: string
            PERMISSIONS:
              type: array
              facets:
                objects:
                  properties:
                    displayName: string
                    id: integer
                    permissionName: string
        example:
          [{
            "displayName": "Manager",
            "PERMISSIONS": [
               {
                  "displayName": "SEND MESSAGES",
                  "id": 15,
                  "permissionName": "SEND MESSAGES"
               },{
                  "displayName": "EDIT JOB STATUS",
                  "id": 5,
                  "permissionName": "EDIT JOB STATUS"
               },{
                  "displayName": "EDIT JOB",
                  "id": 4,
                  "permissionName": "EDIT JOB"
               },{
                  "displayName": "MATCHING",
                  "id": 17,
                  "permissionName": "MATCHING"
               },{
                  "displayName": "ADMINISTRATION",
                  "id": 12,
                  "permissionName": "ADMINISTRATION"
               },{
                  "displayName": "BULK ACTION",
                  "id": 32,
                  "permissionName": "BULK ACTION"
               },{
                  "displayName": "USERMANAGEMENT",
                  "id": 11,
                  "permissionName": "USERMANAGEMENT"
               },{
                  "displayName": "CREATE JOB",
                  "id": 3,
                  "permissionName": "CREATE JOB"
               },{
                  "displayName": "ACCOUNT",
                  "id": 16,
                  "permissionName": "ACCOUNT"
               },{
                  "displayName": "ACTIVITYSTREAM",
                  "id": 8,
                  "permissionName": "ACTIVITYSTREAM"
               },{
                  "displayName": "CANDIDATES",
                  "id": 7,
                  "permissionName": "CANDIDATES"
               },{
                  "displayName": "STATISTICS",
                  "id": 6,
                  "permissionName": "STATISTICS"
               },{
                  "displayName": "TAGMANAGEMENT",
                  "id": 13,
                  "permissionName": "TAGMANAGEMENT"
               },{
                  "displayName": "PUBLISH JOB",
                  "id": 14,
                  "permissionName": "PUBLISH JOB"
               }],
            "id": 10,
            "systemName": "Manager"
            }]
  delete:
    queryParameters:
      roleId:
        required: true

# resetpassword

/resetpassword:
  post:
    body:
      application/json:
        properties:
          secretkey:
            type: string
            required: true
          passWord:
            type: string
            required: true

# registration

/registration:
  post:
    body:
      application/json:
        properties:
          personId:
            required: false
          firstName:
            required: false
          infix:
            required: false
          lastName:
            required: false
          emailaddress:
            required: false
          username:
            required: false
          password:
            required: false
          candidateOrigin:
            required: false

# references

/references:
  is: [ token_required,
    response_delete_nok,
    response_get_nok,
    response_post_nok,
    response_put_nok,
    response_delete_ok,
    response_post_ok,
    response_put_ok ] # this covers all responses except GET 200
  get:
    queryParameters:
      id:
        type: string
        required: false
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: object
              properties:
                displayName: string
                id: string
            example:
              [{
                  "displayName": "H&R",
                  "id": "231017e4-e689-4460-ba93-2445cfb6906f"
               },
               {
                  "displayName": "Marketing",
                  "id": "45a2306d-580a-40c5-b776-f7f972a9667b"
               },
               {
                  "displayName": "Sales",
                  "id": "2b9bd067-7eb4-4222-8707-dac5a84f3d47"
               },
               {
                  "displayName": "Sales",
                  "id": "e1dd39e2-4941-4f81-8411-f3ae9d04c62a"
              }]
  post:
    body:
      application/json:
        properties:
          reference:
            type: object
            required: true
            properties:
              displayName: string
              id: string
          token: string
        example: |
          {
            "reference": {
              "displayName": "Sales",
              "id": ""
              },
          "token": "E4CB8DB5-6C62-6D46-AC1443232464C278"
          }
  put:
    body:
      application/json:
        properties:
          reference:
            type: object
            required: true
            properties:
              displayName: string
              id: string
          token: string
        example: |
          {
            "reference": {
              "displayName": "Sales",
              "id": "e1dd39e2-4941-4f81-8411-f3ae9d04c62a"
              },
          "token": "E4CB8DB5-6C62-6D46-AC1443232464C278"
          }
  delete:
    queryParameters:
     id:
       type: string
       required: true
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                id: string
                displayName: string
              example:
                {
                    "displayName": "H&R",
                    "id": "231017e4-e689-4460-ba93-2445cfb6906f"
                 }

# permission

/permission:
  is: [ token_required,response_get_nok]
  get:
    responses:
      200:
        body:
          application/json:
            type: array
            items:
               type: object
               properties:
                  DisplayName: string
                  id: integer
                  permissionName:  string
            example:
              [
               {
                  "DisplayName": "Vacature bewerken",
                  "id": 3,
                  "permissionName": "CREATE JOB"
               },{
                  "DisplayName": "Vacature aanmaken",
                  "id": 4,
                  "permissionName": "EDIT JOB"
               },{
                  "DisplayName": "Vacature status wijzigen",
                  "id": 5,
                  "permissionName": "EDIT JOB STATUS"
               }
              ]

# matchingconfigurations

/matchingconfigurations:
  is: [ token_required,
    response_delete_nok,
    response_get_nok,
    response_post_nok,
    response_put_nok,
    response_delete_ok,
    response_post_ok,
    response_put_ok ] # this covers all responses except GET 200
  get:
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: object
              properties:
                educationPassed: integer
                experienceLevelBelowZero: integer
                educationLevelExponent: integer
                experienceSubAreaWeight: integer
                experienceWeight: integer
                languageWeight: integer
                traitsExponent: number
                educationWeight: integer
                id: string
                deleted: string
                skillWeight: integer
                experienceLevelWeight: integer
                languageExponent: integer
                name: string
                educationAreaWeight:  integer
                competenceExponent: integer
                experienceAreaWeight: integer
                created: string
                experienceLevelAboveZero: integer
                displayName: string
                competenceWeight: integer
                skillExponent: integer
                educationNotPassed: number
                updated: string
                generalSkillWeight: number
                knowledgeWeight: number
                personalityWeight: integer
                traitsBase: integer
                traitsWeight: number
                domainOwnerId: string
                educationLevelWeight: integer
            example:
              [{
               educationPassed: 1,
               "experienceLevelBelowZero": 1,
               "educationLevelExponent": 2,
               "experienceSubAreaWeight": 1,
               "experienceWeight": 1,
               "languageWeight": 1,
               "traitsExponent": 1.5,
               "educationWeight": 1,
               "id": "4b5d8270-1203-4d2e-be32-7105bff1f0e0",
               "deleted": "",
               "skillWeight": 1,
               "experienceLevelWeight": 1,
               "languageExponent": 2,
               "name": "Basis",
               "educationAreaWeight": 1,
               "competenceExponent": 2,
               "experienceAreaWeight": 1,
               "created": "December, 10 2015 22:36:12",
               "experienceLevelAboveZero": 1,
               "displayName": "Basis",
               "competenceWeight": 1,
               "skillExponent": 2,
               "educationNotPassed": 0.25,
               "updated": "",
               "generalSkillWeight": 1,
               "knowledgeWeight": 1,
               "personalityWeight": 1,
               "traitsBase": 6,
               "traitsWeight": 1.5,
               "domainOwnerId": "83544755-1455-4f88-9cc9-7caf99a6a6b2",
               "educationLevelWeight": 1
            },{
              "educationPassed": 1,
              "experienceLevelBelowZero": 1,
              "educationLevelExponent": 2,
              "experienceSubAreaWeight": 1,
              "experienceWeight": 1,
              "languageWeight": 1,
              "traitsExponent": 1.5,
              "educationWeight": 1,
              "id": "f4aaadd7-d59d-42bc-ba71-fea322ed9cc5",
              "deleted": "",
              "skillWeight": 1,
              "experienceLevelWeight": 1,
              "languageExponent": 2,
              "name": "Marc's set",
              "educationAreaWeight": 1,
              "competenceExponent": 2,
              "experienceAreaWeight": 1,
              "created": "May, 30 2016 15:55:27",
              "experienceLevelAboveZero": 1,
              "displayName": "Marc's set",
              "competenceWeight": 1,
              "skillExponent": 2,
              "educationNotPassed": 0.25,
              "updated": "",
              "generalSkillWeight": 1,
              "knowledgeWeight": 1,
              "personalityWeight": 1,
              "traitsBase": 6,
              "traitsWeight": 1,
              "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2",
              "educationLevelWeight": 1
           },{
              "educationPassed": 1,
              "experienceLevelBelowZero": 1,
              "educationLevelExponent": 2,
              "experienceSubAreaWeight": 1,
              "experienceWeight": 1,
              "languageWeight": 2,
              "traitsExponent": 1.5,
              "educationWeight": 1,
              "id": "bc06a56a-5f40-4187-aa57-d6d13a325211",
              "deleted": "",
              "skillWeight": 2,
              "experienceLevelWeight": 1,
              "languageExponent": 2,
              "name": "test1",
              "educationAreaWeight": 1,
              "competenceExponent": 2,
              "experienceAreaWeight": 1,
              "created": "December, 14 2015 10:30:42",
              "experienceLevelAboveZero": 1,
              "displayName": "test1",
              "competenceWeight": 1,
              "skillExponent": 2,
              "educationNotPassed": 0.25,
              "updated": "",
              "generalSkillWeight": 1,
              "knowledgeWeight": 1,
              "personalityWeight": 1,
              "traitsBase": 6,
              "traitsWeight": 1,
              "domainOwnerId": "83599755-1755-4f77-9c12-7caf99a6a6b2",
              "educationLevelWeight": 1
           }]
  post:
    body:
      application/json:
        type: object
        properties:
          matchingConfiguration:
            type: object
            required: true
            properties:
              educationPassed: integer
              experienceLevelBelowZero: integer
              educationLevelExponent: integer
              experienceSubAreaWeight: integer
              experienceWeight: integer
              languageWeight: integer
              traitsExponent: number
              educationWeight: integer
              id: string
              deleted: string
              skillWeight: integer
              experienceLevelWeight: integer
              languageExponent: integer
              name: string
              educationAreaWeight:  integer
              competenceExponent: integer
              experienceAreaWeight: integer
              created: string
              experienceLevelAboveZero: integer
              displayName: string
              competenceWeight: integer
              skillExponent: integer
              educationNotPassed: number
              updated: string
              generalSkillWeight: integer
              knowledgeWeight: integer
              personalityWeight: integer
              traitsBase: integer
              traitsWeight: number
              domainOwnerId: string
              educationLevelWeight: integer
          token: string
        example: |
          {
           "matchingConfiguration": {
             "educationPassed": 1,
             "experienceLevelBelowZero": 1,
             "educationLevelExponent": 2,
             "experienceSubAreaWeight": 1,
             "experienceWeight": 1,
             "languageWeight": 2,
             "traitsExponent": 1.5,
             "educationWeight": 1,
             "id": "",
             "deleted": "",
             "skillWeight": 2,
             "experienceLevelWeight": 1,
             "languageExponent": 2,
             "name": "test1",
             "educationAreaWeight": 1,
             "competenceExponent": 2,
             "experienceAreaWeight": 1,
             "created": "December, 14 2015 10:30:42",
             "experienceLevelAboveZero": 1,
             "displayName": "test1",
             "competenceWeight": 1,
             "skillExponent": 2,
             "educationNotPassed": 0.25,
             "updated": "",
             "generalSkillWeight": 1,
             "knowledgeWeight": 1,
             "personalityWeight": 1,
             "traitsBase": 6,
             "traitsWeight": 1,
             "domainOwnerId": "83599755-1755-4f77-9c12-7caf99a6a6b2",
             "educationLevelWeight": 1
             },
           "token": "83599555-1755-4f77-9c88-7caf99bda6b2"
          }
  put:
    body:
      application/json:
        type: object
        properties:
          matchingConfiguration:
            type: object
            required: true
            properties:
              educationPassed: integer
              experienceLevelBelowZero: integer
              educationLevelExponent: integer
              experienceSubAreaWeight: integer
              experienceWeight: integer
              languageWeight: integer
              traitsExponent: number
              educationWeight: integer
              id: string
              deleted: string
              skillWeight: integer
              experienceLevelWeight: integer
              languageExponent: integer
              name: string
              educationAreaWeight:  integer
              competenceExponent: integer
              experienceAreaWeight: integer
              created: string
              experienceLevelAboveZero: integer
              displayName: string
              competenceWeight: integer
              skillExponent: integer
              educationNotPassed: number
              updated: string
              generalSkillWeight: integer
              knowledgeWeight: integer
              personalityWeight: integer
              traitsBase: integer
              traitsWeight: number
              domainOwnerId: string
              educationLevelWeight: integer
          token: string
        example: |
          {
           "matchingConfiguration": {
             "educationPassed": 1,
             "experienceLevelBelowZero": 1,
             "educationLevelExponent": 2,
             "experienceSubAreaWeight": 1,
             "experienceWeight": 1,
             "languageWeight": 2,
             "traitsExponent": 1.5,
             "educationWeight": 1,
             "id": "bc06a56a-5f40-4187-aa57-d6d13a325211",
             "deleted": "",
             "skillWeight": 2,
             "experienceLevelWeight": 1,
             "languageExponent": 2,
             "name": "test1",
             "educationAreaWeight": 1,
             "competenceExponent": 2,
             "experienceAreaWeight": 1,
             "created": "December, 14 2015 10:30:42",
             "experienceLevelAboveZero": 1,
             "displayName": "test1",
             "competenceWeight": 1,
             "skillExponent": 2,
             "educationNotPassed": 0.25,
             "updated": "",
             "generalSkillWeight": 1,
             "knowledgeWeight": 1,
             "personalityWeight": 1,
             "traitsBase": 6,
             "traitsWeight": 1,
             "domainOwnerId": "83599755-1755-4f77-9c12-7caf99a6a6b2",
             "educationLevelWeight": 1
             },
           "token": "83599555-1755-4f77-9c88-7caf99bda6b2"
          }
  delete:
    queryParameters:
     matchingId:
       type: string
       required: true
  /{matchingId}:
    get:
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                educationPassed: integer
                experienceLevelBelowZero: integer
                educationLevelExponent: integer
                experienceSubAreaWeight: integer
                experienceWeight: integer
                languageWeight: integer
                traitsExponent: number
                educationWeight: integer
                id: string
                deleted: string
                skillWeight: integer
                experienceLevelWeight: integer
                languageExponent: integer
                name: string
                educationAreaWeight:  integer
                competenceExponent: integer
                experienceAreaWeight: integer
                created: string
                experienceLevelAboveZero: integer
                displayName: string
                competenceWeight: integer
                skillExponent: integer
                educationNotPassed: number
                updated: string
                generalSkillWeight: integer
                knowledgeWeight: integer
                personalityWeight: integer
                traitsBase: integer
                traitsWeight: number
                domainOwnerId: string
                educationLevelWeight: integer
              example:
                {
                 "educationPassed": 1,
                 "experienceLevelBelowZero": 1,
                 "educationLevelExponent": 2,
                 "experienceSubAreaWeight": 1,
                 "experienceWeight": 1,
                 "languageWeight": 1,
                 "traitsExponent": 1.5,
                 "educationWeight": 1,
                 "id": "4b5d8270-1203-4d2e-be44-7105bac1f0e0",
                 "deleted": "",
                 "skillWeight": 1,
                 "experienceLevelWeight": 1,
                 "languageExponent": 2,
                 "name": "Basis",
                 "educationAreaWeight": 1,
                 "competenceExponent": 2,
                 "experienceAreaWeight": 1,
                 "created": "December, 10 2015 22:36:12",
                 "experienceLevelAboveZero": 1,
                 "displayName": "Basis",
                 "competenceWeight": 1,
                 "skillExponent": 2,
                 "educationNotPassed": 0.25,
                 "updated": "",
                 "generalSkillWeight": 1,
                 "knowledgeWeight": 1,
                 "personalityWeight": 1,
                 "traitsBase": 6,
                 "traitsWeight": 1.5,
                 "domainOwnerId": "83599325-1834-4f88-9c09-7ce399a6a6b2",
                 "educationLevelWeight": 1
              }

# logout

/logout:
  is: [response_post_ok,response_post_nok]
  post:
    body:
      application/json:
        properties:
          tokens:
            type: string
            required: false
        example:
          {
             "tokens": "83665325-1834-9d88-9c09-7ce398b6a6b2"
          }
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              message: string
            example: |
              {
                 "message": "LOGOUT_OK"
              }

# login

/login:
  post:
    body:
      application/json:
        properties:
          username:
            required: true
            type: string
          password:
            required: true
            type: string
          deviceId:
            required: false
            type: string
          domainId:
            required: true
            type: string
        example:
          {
            "deviceId": "",
            "domainId": "6ead3b9b-511d-4976-8179-05f3e24e3231",
            "username": "peter@hrmatches.com",
            "password": "peter123"
          }
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              message: string
              token: string
            example: |
              {
                 "message": "LOGIN_OK",
                 "token": "7FDAA98D-6C62-6D46-AC14847F95F7579F"
              }
      404:
        body:
          application/json:
            type: object
            properties:
              message: string
            example: |
              {
                 "message": "LOGIN_ERROR"
              }
/language:
  is: [token_optional,response_get_nok]
  get:
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: object
              properties:
                lv_LV_DisplayName: string
                name: string
                en_US_DisplayName: string
                en_GB_DisplayName: string
                fallback: integer
                es_ES_DisplayName: string
                created: string
                available: integer
                de_DE_DisplayName: string
                nl_NL_DisplayName: string
                ru_RU_DisplayName: string
                updated: string
                id: integer
                master: number
                pl_PL_DisplayName: string
                pt_PT_DisplayName: string
                verified: number
                fr_FR_DisplayName: string
                ISO639x: string
                code: string
            example:
              [{
                "lv_LV_DisplayName": "Deutsch - Germany",
                "name": "de_DE",
                "en_US_DisplayName": "German - Germany",
                "en_GB_DisplayName": "German - Germany",
                "fallback": 38,
                "es_ES_DisplayName": "Deutsch - Germany",
                "created": "July, 22 2015 14:36:46",
                "available": 1,
                "de_DE_DisplayName": "Deutsch - Deutschland",
                "nl_NL_DisplayName": "Duits - Germany",
                "ru_RU_DisplayName": "Deutsch - Germany",
                "updated": "",
                "id": 65,
                "master": 1,
                "pl_PL_DisplayName": "Deutsch - Niemcy",
                "pt_PT_DisplayName": "Deutsch - Germany",
                "verified": 1,
                "fr_FR_DisplayName": "Deutsch - Allemagne",
                "ISO639x": " ",
                "code": "0x040"
              },{
                "lv_LV_DisplayName": "Deutsch - Germany",
                "name": "de_DE",
                "en_US_DisplayName": "German - Germany",
                "en_GB_DisplayName": "German - Germany",
                "fallback": 38,
                "es_ES_DisplayName": "Deutsch - Germany",
                "created": "July, 22 2015 14:36:46",
                "available": 1,
                "de_DE_DisplayName": "Deutsch - Deutschland",
                "nl_NL_DisplayName": "Duits - Germany",
                "ru_RU_DisplayName": "Deutsch - Germany",
                "updated": "",
                "id": 65,
                "master": 1,
                "pl_PL_DisplayName": "Deutsch - Niemcy",
                "pt_PT_DisplayName": "Deutsch - Germany",
                "verified": 1,
                "fr_FR_DisplayName": "Deutsch - Allemagne",
                "ISO639x": " ",
                "code": "0x040"
              },{
                "lv_LV_DisplayName": "English - United States",
                "name": "en_US",
                "en_US_DisplayName": "English - United States",
                "en_GB_DisplayName": "English - United States",
                "fallback": 38,
                "es_ES_DisplayName": "English - United States",
                "created": "July, 22 2015 14:36:46",
                "available": 1,
                "de_DE_DisplayName": "Englisch - Vereinigte Staaten",
                "nl_NL_DisplayName": "Engels - United States",
                "ru_RU_DisplayName": "English - United States",
                "updated": "",
                "id": 50,
                "master": 1,
                "pl_PL_DisplayName": "Angielski - Stany Zjednoczone",
                "pt_PT_DisplayName": "English - United States",
                "verified": 1,
                "fr_FR_DisplayName": "Anglais- États Unis",
                "ISO639x": "ENU",
                "code": "0x040"
             }]
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                lv_LV_DisplayName: string
                name: string
                en_US_DisplayName: string
                en_GB_DisplayName: string
                fallback: integer
                es_ES_DisplayName: string
                created: string
                available: integer
                de_DE_DisplayName: string
                nl_NL_DisplayName: string
                ru_RU_DisplayName: string
                updated: string
                id: integer
                master: number
                pl_PL_DisplayName: string
                pt_PT_DisplayName: string
                verified: number
                fr_FR_DisplayName: string
                ISO639x: string
                code: string
              example:
                {
                  "lv_LV_DisplayName": "Russian - Russia",
                  "name": "ru_RU",
                  "en_US_DisplayName": "Russian - Russia",
                  "en_GB_DisplayName": "Russian - Russia",
                  "fallback": 38,
                  "es_ES_DisplayName": "Russian - Russia",
                  "created": "July, 22 2015 14:36:46",
                  "available": 1,
                  "de_DE_DisplayName": "Russisch",
                  "nl_NL_DisplayName": "Russisch - Russia",
                  "ru_RU_DisplayName": "Russian - Russia",
                  "updated": "",
                  "id": 98,
                  "master": 1,
                  "pl_PL_DisplayName": "Rosyjski",
                  "pt_PT_DisplayName": "Russian - Russia",
                  "verified": 1,
                  "fr_FR_DisplayName": "Russe",
                  "ISO639x": "RUS",
                  "code": "0x041"
              }

/jobs:
  is: [token_required,response_get_nok]
  get:
    description: List all jobs
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: object
              properties:
                jobDomainId: string
                domainOwnerDeleted: string
                teamId: string
                JobId: string
                roleId: integer
                jobStatus: integer
                PersonId: string
                firstName: string
                NumberInStatus: integer
                infix: string
                domainOwnerName: string
                JobApplicationStatusId: integer
                jobName: string
                domainOwnerId: string
                emailaddress: string
                lastName: string
            example:
                [{
                    "jobDomainId": "8de47fd3-355f-4912-aa37-6d072e68a943",
                    "domainOwnerDeleted": "",
                    "teamId": "4c387f21-01b8-448e-adef-1b17739023c8",
                    "JobId": "b1772b18-a68f-4655-89d3-c6131c260e9a",
                    "roleId": 61,
                    "jobStatus": 1,
                    "PersonId": "7152db9e-b1af-41ac-aacf-a6a1f4f91170",
                    "firstName": "Demo",
                    "NumberInStatus": 2,
                    "infix": "",
                    "domainOwnerName": "Demo",
                    "JobApplicationStatusId": 1,
                    "jobName": "Business intelligence consultant",
                    "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2",
                    "emailaddress": "demo@hrmatches.com",
                    "lastName": "HRMatches"
                 },{
                    "jobDomainId": "8de47fd3-355f-4912-aa37-6d072e68a943",
                    "domainOwnerDeleted": "",
                    "teamId": "4c387f21-01b8-448e-adef-1b17849023c8",
                    "JobId": "236cfd01-cb96-4dde-818a-78985619e1df",
                    "roleId": 61,
                    "jobStatus": 1,
                    "PersonId": "7152db9e-b1af-41ac-aacf-a6a1f4f91170",
                    "firstName": "Demo",
                    "NumberInStatus": 1,
                    "infix": "",
                    "domainOwnerName": "Demo",
                    "JobApplicationStatusId": 1,
                    "jobName": "jhkgghjgkjb jh jul",
                    "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2",
                    "emailaddress": "demo@hrmatches.com",
                    "lastName": "HRMatches"
                 }]
  /{jobId}:
    get:
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                jobDomainId: string
                domainOwnerDeleted: string
                teamId: string
                JobId: string
                roleId: integer
                jobStatus: integer
                PersonId: string
                firstName: string
                NumberInStatus: integer
                infix: string
                domainOwnerName: string
                JobApplicationStatusId: integer
                jobName: string
                domainOwnerId: string
                emailaddress: string
                lastName: string
              example:
                {
                "jobDomainId": "8de47fd3-355f-4912-aa37-6d072e68a943",
                "domainOwnerDeleted": "",
                "teamId": "4c387f21-01b8-448e-adef-1b17849023c8",
                "JobId": "236cfd01-cb96-4dde-818a-78985619e1df",
                "roleId": 61,
                "jobStatus": 1,
                "PersonId": "7152db9e-b1af-41ac-aacf-a6a1f4f91170",
                "firstName": "Demo",
                "NumberInStatus": 1,
                "infix": "",
                "domainOwnerName": "Demo",
                "JobApplicationStatusId": 1,
                "jobName": "jhkgghjgkjb jh jul",
                "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2",
                "emailaddress": "demo@hrmatches.com",
                "lastName": "HRMatches"
                }

/jobdomains:
  is: [ token_required,
    response_delete_nok,
    response_get_nok,
    response_post_nok,
    response_put_nok,
    response_delete_ok,
    response_post_ok,
    response_put_ok ] # this covers all responses except GET 200
  get:
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: object
              properties:
                parent: string
                displayName: string
                id: string
                companyCultureId: string
                matchingId: string
                domainOwnerId: string
            example:
              [{
                  "parent": "a5758488-8204-4e36-808b-eeb938d8811f",
                  "displayName": "ICT Mobile",
                  "id": "d4ec4733-b0a3-4b88-bd56-3d8c99729e41",
                  "companyCultureId": "",
                  "matchingId": "",
                  "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2"
               },{
                  "parent": "",
                  "displayName": "Logistics",
                  "id": "e6dc8cb5-8267-410d-af47-4c08337423d7",
                  "companyCultureId": "324517b2-9830-45b3-9b18-eee8c48d18a7",
                  "matchingId": "4b5d8270-1203-4d2e-be32-7105bff1f0e0",
                  "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2"
               },{
                  "parent": "",
                  "displayName": "demo",
                  "id": "8de47fd3-355f-4912-aa37-6d072e68a943",
                  "companyCultureId": "eff89f65-3a35-4a7d-9b05-27041e19fadb",
                  "matchingId": "4b5d8270-1203-4d2e-be32-7105bff1f0e0",
                  "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2"
               },{
                  "parent": "",
                  "displayName": "HR",
                  "id": "c4f46d47-4059-4dfb-a54a-874d35c5cb8d",
                  "companyCultureId": "8d6513df-94d0-4be2-bda7-a0945062c94f",
                  "matchingId": "4b5d8270-1203-4d2e-be32-7105bff1f0e0",
                  "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2"
               },{
                  "parent": "",
                  "displayName": "Marketing",
                  "id": "417fd32c-ca2e-4e51-9b7c-e0e25df1cabd",
                  "companyCultureId": "",
                  "matchingId": "",
                  "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2"
               },{
                  "parent": "",
                  "displayName": "ICT",
                  "id": "a5758488-8204-4e36-808b-eeb938d8811f",
                  "companyCultureId": "8d6513df-94d0-4be2-bda7-a0945062c94f",
                  "matchingId": "bc06a56a-5e40-4187-aa57-d8b13a325211",
                  "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2"
                 }]
  post:
    body:
      application/json:
        type: object
        properties:
          jobdomains:
            required: true
            type: object
            properties:
              parent: string
              displayName: string
              id: string
              companyCultureId: string
              matchingId: string
              domainOwnerId: string
        example: |
          {
             "jobdomains": {
                "parent": "",
                "displayName": "New",
                "id": "a5758488-8204-4e36-808b-eeb938d8811f",
                "companyCultureId": "8d6513df-94d0-4be2-bda7-a0945062c94f",
                "matchingId": "bc06a56a-5e40-4187-aa57-d8b13a325211",
                "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2"
               }
          }
  put:
    body:
      application/json:
        type: object
        properties:
          jobdomains:
            required: true
            type: object
            properties:
              parent: string
              displayName: string
              id: string
              companyCultureId: string
              matchingId: string
              domainOwnerId: string
        example: |
          {
            "jobdomains": {
               "parent": "",
               "displayName": "HR",
               "id": "c4f46d47-4059-4dfb-a54a-874d35c5cb8d",
               "companyCultureId": "8d6513df-94d0-4be2-bda7-a0945062c94f",
               "matchingId": "4b5d8270-1203-4d2e-be32-7105bff1f0e0",
               "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2"
            }
          }
  delete:
    queryParameters:
      jobDomainId:
        type: string
        required: true
  /{jobDomainId}:
    get:
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                parent: string
                displayName: string
                id: string
                companyCultureId: string
                matchingId: string
                domainOwnerId: string
              example:
                {
                   "parent": "",
                   "displayName": "Marketing",
                   "id": "417fd32c-ca2e-4e51-9b7c-e0e25df1cabd",
                   "companyCultureId": "",
                   "matchingId": "",
                   "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2"
                }

/forgotpassword:
  post:
    body:
      application/json:
        properties:
          emailaddress:
            required: true
          hostname:
            required: false
        example: |
          {
           "hostname": "",
           "emailaddress": ""
          }

/educationtype:
  is: [token_required,response_get_nok]
  get:
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: object
              properties:
                lv_LV_DisplayName: string
                description: string
                en_US_DisplayName: string
                en_GB_DisplayName: string
                es_ES_DisplayName: string
                created: string
                de_DE_DisplayName: string
                nl_NL_DisplayName: string
                otmEducationId: integer
                ru_RU_DisplayName: string
                updated: string
                id: string
                educationTypeOrder: integer
                pl_PL_DisplayName: string
                pt_PT_DisplayName: string
                fr_FR_DisplayName: string
                deleted: string
                educationType: string
                type: integer
            example:
                [{
                  "lv_LV_DisplayName": "",
                  "description": "HBO/bachelor",
                  "en_US_DisplayName": "Bachelor",
                  "en_GB_DisplayName": "",
                  "es_ES_DisplayName": "",
                  "created": "September, 24 2015 10:05:59",
                  "de_DE_DisplayName": "Bachelor",
                  "nl_NL_DisplayName": "Bachelor",
                  "otmEducationId": 6,
                  "ru_RU_DisplayName": "",
                  "updated": "",
                  "id": "03d2f673-6f0f-44d4-b044-1c520b0b2023",
                  "educationTypeOrder": 3,
                  "pl_PL_DisplayName": "Licence/Bac+3",
                  "pt_PT_DisplayName": "",
                  "fr_FR_DisplayName": "Bachelor",
                  "deleted": "",
                  "educationType": "HBO/bachelor",
                  "type": 1
               },
               {
                  "lv_LV_DisplayName": "",
                  "description": "WO/Master",
                  "en_US_DisplayName": "Master ",
                  "en_GB_DisplayName": "",
                  "es_ES_DisplayName": "",
                  "created": "September, 24 2015 10:06:17",
                  "de_DE_DisplayName": "Master ",
                  "nl_NL_DisplayName": "Master",
                  "otmEducationId": 7,
                  "ru_RU_DisplayName": "",
                  "updated": "",
                  "id": "e8cc0a1d-b7d9-44af-8641-215fe76d8a7e",
                  "educationTypeOrder": 4,
                  "pl_PL_DisplayName": "Master ",
                  "pt_PT_DisplayName": "",
                  "fr_FR_DisplayName": "Master ",
                  "deleted": "",
                  "educationType": "WO/Master",
                  "type": 1
               },
               {
                  "lv_LV_DisplayName": "",
                  "description": "HAVO",
                  "en_US_DisplayName": "High school",
                  "en_GB_DisplayName": "",
                  "es_ES_DisplayName": "",
                  "created": "March, 26 2015 16:22:49",
                  "de_DE_DisplayName": "Haupt-/Realschulabschluss oder gleichwertig",
                  "nl_NL_DisplayName": "HAVO",
                  "otmEducationId": 3,
                  "ru_RU_DisplayName": "",
                  "updated": "",
                  "id": "2a5a9712-a5b8-4df8-982a-319c2c39a552",
                  "educationTypeOrder": 3,
                  "pl_PL_DisplayName": "Podstawowe",
                  "pt_PT_DisplayName": "",
                  "fr_FR_DisplayName": "Enseignement primaire",
                  "deleted": "March, 26 2015 16:22:49",
                  "educationType": "HAVO",
                  "type": 1
               }]
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              type: object
              example:
                {
                   "lv_LV_DisplayName": "",
                   "description": "HAVO",
                   "en_US_DisplayName": "High school",
                   "en_GB_DisplayName": "",
                   "es_ES_DisplayName": "",
                   "created": "March, 26 2015 16:22:49",
                   "de_DE_DisplayName": "Haupt-/Realschulabschluss oder gleichwertig",
                   "nl_NL_DisplayName": "HAVO",
                   "otmEducationId": 3,
                   "ru_RU_DisplayName": "",
                   "updated": "",
                   "id": "2a5a9712-a5b8-4df8-982a-319c2c39a552",
                   "educationTypeOrder": 3,
                   "pl_PL_DisplayName": "Podstawowe",
                   "pt_PT_DisplayName": "",
                   "fr_FR_DisplayName": "Enseignement primaire",
                   "deleted": "March, 26 2015 16:22:49",
                   "educationType": "HAVO",
                   "type": 1
                }

/cultures:
  is: [ token_required,
    response_delete_nok,
    response_get_nok,
    response_post_nok,
    response_put_nok,
    response_delete_ok,
    response_post_ok,
    response_put_ok ] # this covers all responses except GET 200
  get:
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: object
              properties:
                ADHO: integer
                DisplayName: string
                name: string
                companyDefault: integer
                FAML: integer
                updated: string
                MRKT: integer
                id: string
                HCHY: integer
                created: string
                domainOwnerId: string
            example:
                [{
                  "ADHO": 3,
                  "DisplayName": "Basis cultuur",
                  "name": "Basis cultuur",
                  "companyDefault": 1,
                  "FAML": 2,
                  "updated": "",
                  "MRKT": 2,
                  "id": "eff89f65-3a35-4a7d-9b05-27041e19fadb",
                  "HCHY": 1,
                  "created": "December, 03 2015 00:45:38",
                  "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2"
               },{
                  "ADHO": 3,
                  "DisplayName": "Cultuur 1",
                  "name": "Cultuur 1",
                  "companyDefault": 1,
                  "FAML": 7,
                  "updated": "",
                  "MRKT": 6,
                  "id": "8d6513df-94d0-4be2-bda7-a0945062c94f",
                  "HCHY": 2,
                  "created": "December, 14 2015 10:29:18",
                  "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2"
               },{
                "ADHO": 9,
                  "DisplayName": "Cultuur 3",
                  "name": "Cultuur 3",
                  "companyDefault": 1,
                  "FAML": 4,
                  "updated": "",
                  "MRKT": 7,
                  "id": "e0783eab-a6ed-4af5-bae4-20bb53c9a98e",
                  "HCHY": 2,
                  "created": "December, 14 2015 10:36:47",
                  "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2"
               }]
  post:
    body:
      application/json:
        type: object
        properties:
          culture:
            type: object
            required: true
            properties:
              ADHO: integer
              DisplayName: string
              name: string
              companyDefault: integer
              FAML: integer
              updated: string
              MRKT: integer
              id: string
              HCHY: integer
              created: string
              domainOwnerId: string
          token: string
        example: |
          {
          "culture": {
            "ADHO": 9,
              "DisplayName": "Cultuur 3",
              "name": "Cultuur 3",
              "companyDefault": 1,
              "FAML": 4,
              "updated": "",
              "MRKT": 7,
              "id": "",
              "HCHY": 2,
              "created": "December, 14 2015 10:36:47",
              "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2"
            },
            "token": "E4CB9DB5-6C62-6D46-AC1443222464C278"
          }
  put:
    body:
      application/json:
        type: object
        properties:
          culture:
            type: object
            required: true
            properties:
              ADHO: integer
              DisplayName: string
              name: string
              companyDefault: integer
              FAML: integer
              updated: string
              MRKT: integer
              id: string
              HCHY: integer
              created: string
              domainOwnerId: string
          token: string
        example: |
          {
          "culture": {
            "ADHO": 9,
              "DisplayName": "Cultuur 3",
              "name": "Cultuur 3",
              "companyDefault": 1,
              "FAML": 4,
              "updated": "",
              "MRKT": 7,
              "id": "8d6513df-94d0-4be2-bda7-a0945062c94f",
              "HCHY": 2,
              "created": "December, 14 2015 10:36:47",
              "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2"
            },
            "token": "E4CB9DB5-6C62-6D46-AC1443222464C278"
          }
  delete:
    queryParameters:
      id:
        type: string
        required: true
  /{cultureId}:
    get:
      responses:
        200:
          body:
            application/json:
              type: object
              example:
                {
                 "ADHO": 9,
                 "DisplayName": "Cultuur 3",
                 "name": "Cultuur 3",
                 "companyDefault": 0,
                 "FAML": 4,
                 "updated": "",
                 "MRKT": 7,
                 "id": "e0783eab-a6ed-4af5-bae4-20bb53c9a98e",
                 "HCHY": 2,
                 "created": "December, 14 2015 10:36:47",
                 "domainOwnerId": "83599755-1855-4f88-9c09-7caf99a6a6b2"
                }

/country:
  is: [token_required,response_get_nok]
  get:
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: object
              properties:
                lv_LV_DisplayName: string
                en_US_DisplayName: string
                en_GB_DisplayName: string
                be_BE_DisplayName: string
                es_ES_DisplayName: string
                created: string
                de_DE_DisplayName: string
                nl_NL_DisplayName: string
                countryName: string
                ru_RU_DisplayName: string
                updated: string
                id: string
                pl_PL_DisplayName: string
                pt_PT_DisplayName: string
                fr_FR_DisplayName: string
            example:
              [{
                "lv_LV_DisplayName": "",
                "en_US_DisplayName": "Afghanistan",
                "en_GB_DisplayName": "Afghanistan",
                "be_BE_DisplayName": "",
                "es_ES_DisplayName": "",
                "created": "July, 21 2015 17:35:35",
                "de_DE_DisplayName": "Afghanistan",
                "nl_NL_DisplayName": "Afghanistan",
                "countryName": "Afghanistan",
                "ru_RU_DisplayName": "",
                "updated": "",
                "id": "AF",
                "pl_PL_DisplayName": "",
                "pt_PT_DisplayName": "",
                "fr_FR_DisplayName": ""
             },{
                "lv_LV_DisplayName": "",
                "en_US_DisplayName": "Åland Islands",
                "en_GB_DisplayName": "Åland Islands",
                "be_BE_DisplayName": "",
                "es_ES_DisplayName": "",
                "created": "July, 21 2015 17:35:35",
                "de_DE_DisplayName": "&Aring;land-Inseln",
                "nl_NL_DisplayName": "Alandeilanden",
                "countryName": "Alandeilanden",
                "ru_RU_DisplayName": "",
                "updated": "",
                "id": "AX",
                "pl_PL_DisplayName": "",
                "pt_PT_DisplayName": "",
                "fr_FR_DisplayName": ""
             },{
                "lv_LV_DisplayName": "",
                "en_US_DisplayName": "Albania",
                "en_GB_DisplayName": "Albania",
                "be_BE_DisplayName": "",
                "es_ES_DisplayName": "",
                "created": "July, 21 2015 17:35:35",
                "de_DE_DisplayName": "Albanien",
                "nl_NL_DisplayName": "Albanië",
                "countryName": "Albanië",
                "ru_RU_DisplayName": "",
                "updated": "",
                "id": "AL",
                "pl_PL_DisplayName": "",
                "pt_PT_DisplayName": "",
                "fr_FR_DisplayName":  ""
             }]
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              type: object
              example:
                {
                   "lv_LV_DisplayName": "",
                   "en_US_DisplayName": "Albania",
                   "en_GB_DisplayName": "Albania",
                   "be_BE_DisplayName": "",
                   "es_ES_DisplayName": "",
                   "created": "July, 21 2015 17:35:35",
                   "de_DE_DisplayName": "Albanien",
                   "nl_NL_DisplayName": "Albanië",
                   "countryName": "Albanië",
                   "ru_RU_DisplayName": "",
                   "updated": "",
                   "id": "AL",
                   "pl_PL_DisplayName": "",
                   "pt_PT_DisplayName": "",
                   "fr_FR_DisplayName":  ""
                }
/companyinfo:
  is: [token_required,response_get_nok,response_put_ok,response_put_nok]
  get:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              countryId: string
              companyAddress: string
              brancheId: string
              companyName: string
              id: string
              companySize: string
              city: string
              contactName: string
              companyDescription: string
              companyZipcode: string
              contactPhoneNumber: string
              website: string
            example:
              {
               "countryId": "",
               "companyAddress": "",
               "brancheId": "",
               "companyName": "Demo",
               "id": "83599755-1855-4f88-9c09-7caf99a6a6b2",
               "companySize": "",
               "city": "",
               "contactName": "",
               "companyDescription": "",
               "companyZipcode": "",
               "contactPhoneNumber": "",
               "website": "demo.hrmatches.com"
          }
  put:
    body:
      application/json:
        type: object
        properties:
          companyinfo:
            required: true
            type: object
            properties:
              countryId: string
              companyAddress: string
              brancheId: string
              companyName: string
              id: string
              companySize: string
              city: string
              contactName: string
              companyDescription: string
              companyZipcode: string
              contactPhoneNumber: string
              website: string
          token:
            required: true

/branche:
  is: [token_required,response_get_nok]
  get:
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: object
              properties:
                brancheName: string
                lv_LV_DisplayName: string
                en_US_DisplayName: string
                en_GB_DisplayName: string
                es_ES_DisplayName: string
                created: string
                de_DE_DisplayName: string
                nl_NL_DisplayName: string
                displayName: string
                updated: string
                ru_RU_DisplayName: string
                id: string
                pl_PL_DisplayName: string
                pt_PT_DisplayName: string
                fr_FR_DisplayName: string
            example:
              [{
                "brancheName": "Accounting en Controlling",
                "lv_LV_DisplayName": "",
                "en_US_DisplayName": "Accounting and Auditing Services",
                "en_GB_DisplayName": "Accounting and Auditing Services",
                "es_ES_DisplayName": "",
                "created": "June, 09 2015 15:58:59",
                "de_DE_DisplayName": "Buchhaltung/Steuer- und Prüfungswesen",
                "nl_NL_DisplayName": "Accounting en Controlling",
                "displayName": "Accounting en Controlling",
                "updated": "",
                "ru_RU_DisplayName": "",
                "id": "c420e11b-7b74-4b34-8df6-04317bdefdd3",
                "pl_PL_DisplayName": "Rachunkowość i controlling",
                "pt_PT_DisplayName": "",
                "fr_FR_DisplayName": "Comptabilité et contrôle de gestion"
             },{
                "brancheName": "Afval en milieu",
                "lv_LV_DisplayName": "",
                "en_US_DisplayName": "Waste Management",
                "en_GB_DisplayName": "Waste Management",
                "es_ES_DisplayName": "",
                "created": "June, 09 2015 15:58:59",
                "de_DE_DisplayName": "Abfallwirtschaft",
                "nl_NL_DisplayName": "Afval en milieu",
                "displayName": "Afval en milieu",
                "updated": "",
                "ru_RU_DisplayName": "",
                "id": "16d5e9d8-345f-48af-a16a-04bb70057162",
                "pl_PL_DisplayName": "Odpady i środowisko",
                "pt_PT_DisplayName": "",
                "fr_FR_DisplayName": "Déchets et environnement"
             },{
                "brancheName": "Architectuur / Design",
                "lv_LV_DisplayName": "",
                "en_US_DisplayName": "Architectural and Design Services",
                "en_GB_DisplayName": "Architectural and Design Services",
                "es_ES_DisplayName": "",
                "created": "June, 09 2015 15:58:59",
                "de_DE_DisplayName": "Architektur/Design",
                "nl_NL_DisplayName": "Architectuur / Design",
                "displayName": "Architectuur / Design",
                "updated": "",
                "ru_RU_DisplayName": "",
                "id": "dca0ffec-9ab9-4803-a206-099bd8357751",
                "pl_PL_DisplayName": "Architektura / projektowanie",
                "pt_PT_DisplayName": "",
                "fr_FR_DisplayName": "Architecture / Design"
             }]

/authenticate:
  is: [token_required,response_post_nok]
  post:
    body:
      application/json:
        properties:
          username:
            type: string
            required: true
          password:
            type: string
            required: true
        example:
          {
            "username": "peter@hrmatches.com",
            "password": "peter123"
          }
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              message: string
              profiles:
                type: array
                required: false
                items:
                  type: object
                  properties:
                    domainOwner: string
                    domainId: string
                    firstName: string
                    infix: string
                    domainName: string
                    loggedIn: string
                    website: string
                    lastName: string
                    personId: string
            example:
              {
               "message": "LOGIN_OK",
               "profiles": [
                  {
                     "domainOwner": "Demo",
                     "domainId": "d70695c2-61a4-472e-8342-f2c4d23c8eab",
                     "firstName": "Demo",
                     "infix": "",
                     "domainName": "HR Domain",
                     "loggedIn": "d70695c2-61a4-472e-8342-f2c4d23c8eaE",
                     "website": "demo.hrmatches.com",
                     "lastName": "HRMatches",
                     "personId": "d70695c2-61a4-472e-8342-f2c4d23g8eab"
                  },{
                     "domainOwner": "Demo",
                     "domainId": "ac06c0de-fa93-4d2b-g3b6-8a8f2a25a9dc",
                     "firstName": "Demo",
                     "infix": "",
                     "domainName": "Site users",
                     "loggedIn": "",
                     "website": "demo.hrmatches.com",
                     "lastName": "HRMatches",
                     "personId": "ac06c0de-fa93-4h2b-a6b6-8b8f2a25a9dc"
                  },{
                     "domainOwner": "UWV",
                     "domainId": "e43e7b77-4e1b-48ad-a461-856b019fd3e9",
                     "firstName": "Demo",
                     "infix": "",
                     "domainName": "Site users",
                     "loggedIn": "",
                     "website": "ontdekjouwtalent.nl",
                     "lastName": "HRMatches",
                     "personId": "e43e7b77-4e1b-48ad-a4r1-856b019fd3e9"
                  }
               ]
            }

/activityLog:
  is: [ token_required,response_get_nok]
  get:
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: object
              properties:
                activity: string
                jobId: string
                jobStatus: string
                created: string
                activityType: string
                jobApplicationId: string
                jobApplicationStatus: string
                personId: string
                firstName: string
                infix: string
                jobStatusId: string
                employeeInfix: string
                id: string
                jobApplicationStatusId: integer
                employeeLastName: string
                jobName: string
                activityTypeId: integer
                employeeFirstName: string
                domainOwnerId: string
                lastName: string
            example:
              [{
                "activity": "",
                "jobId": "b1462b18-a68f-4335-7684-c6130c260e9a",
                "jobStatus": "",
                "created": "May, 23 2016 14:35:47",
                "activityType": "Applied status",
                "jobApplicationId": "9c6fbdc3-fi49-4b00-dd51-cc8a07f870a1",
                "jobApplicationStatus": "NEW",
                "personId": "b31fe3da-f932-4bdb-b45e-5535cd3082cd2",
                "firstName": "Eusebio",
                "infix": "",
                "jobStatusId": "",
                "employeeInfix": "",
                "id": "50ef67cc-5a088-4677-92bf-e467e03343f7",
                "jobApplicationStatusId": 1,
                "employeeLastName": "Daniel",
                "jobName": "Business intelligence consultant",
                "activityTypeId": 6,
                "employeeFirstName": "Eusebio",
                "domainOwnerId": "83599755-1190-4f88-9ca9-7caf99a6a6b2",
                "lastName": "Daniel"
             },{
                "activity": "",
                "jobId": "236cfd01-cb96-4dda-818a-78984319e1df",
                "jobStatus": "",
                "created": "May, 23 2016 14:16:54",
                "activityType": "Applied status",
                "jobApplicationId": "8bdb5e92-331b-46cf-8a11-2cbe225d6583",
                "jobApplicationStatus": "NEW",
                "personId": "7e6aadb9-e366-41f2-8590-323f2d3332b8",
                "firstName": "Eusebio",
                "infix": "",
                "jobStatusId": "",
                "employeeInfix": "",
                "id": "738b898b-6cc8-4a52-bd75-0c67f50e2d27",
                "jobApplicationStatusId": 1,
                "employeeLastName": "Daniel",
                "jobName": "jhkgghjgkjb jh jul",
                "activityTypeId": 6,
                "employeeFirstName": "Eusebio",
                "domainOwnerId": "83596655-1855-2f88-9c09-6caf9326a6b2",
                "lastName": "Daniel"
             },{
                "activity": "",
                "jobId": "b1772b18-a68f-4635-89d3-c6130f360e9a",
                "jobStatus": "",
                "created": "May, 23 2016 14:16:26",
                "activityType": "Applied status",
                "jobApplicationId": "5375b2de-d8b5-42d6-86e2-3c9523ba5e36",
                "jobApplicationStatus": "NEW",
                "personId": "c02dd930-7a5b-467d-a3d2-c46868a5eeff",
                "firstName": "Daniel",
                "infix": "",
                "jobStatusId": "",
                "employeeInfix": "",
                "id": "10f939f1-3e52-42cd-89dd-7b74faeabe24",
                "jobApplicationStatusId": 1,
                "employeeLastName": "Eusebio Roque",
                "jobName": "Business intelligence consultant",
                "activityTypeId": 6,
                "employeeFirstName": "Daniel",
                "domainOwnerId": "83599755-1955-4f48-9c83-7caf99a6a6b2",
                "lastName": "Eusebio Roque"
             }]
  /{jobId}:
    get:
      responses:
        200:
          body:
            application/json:
              type: object
              example:
                {
                   "activity": "",
                   "jobId": "b1772b18-a68f-4635-89d3-c6130f360e9a",
                   "jobStatus": "",
                   "created": "May, 23 2016 14:16:26",
                   "activityType": "Applied status",
                   "jobApplicationId": "5375b2de-d8b5-42d6-86e2-3c9523ba5e36",
                   "jobApplicationStatus": "NEW",
                   "personId": "c02dd930-7a5b-467d-a3d2-c46868a5eeff",
                   "firstName": "Daniel",
                   "infix": "",
                   "jobStatusId": "",
                   "employeeInfix": "",
                   "id": "10f939f1-3e52-42cd-89dd-7b74faeabe24",
                   "jobApplicationStatusId": 1,
                   "employeeLastName": "Eusebio Roque",
                   "jobName": "Business intelligence consultant",
                   "activityTypeId": 6,
                   "employeeFirstName": "Daniel",
                   "domainOwnerId": "83599755-1955-4f48-9c83-7caf99a6a6b2",
                   "lastName": "Eusebio Roque"
                }

/account:
  is: [ token_required,
    response_delete_nok,
    response_get_nok,
    response_put_nok,
    response_delete_ok,
    response_put_ok ] # this covers all responses except GET 200
  get:
    queryParameters:
      personId:
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              firstName: string
              phoneNumber: string
              infix: string
              language: string
              id: string
              emailaddress: string
              lastName: string
            example:
              {
               "firstName": "demo",
               "phoneNumber": "",
               "infix": "",
               "language": "nl_NL",
               "id": "7142d9e-b1be-41ac-bbcf-a6a1f4d31170",
               "emailaddress": "demo@hrmatches.com",
               "lastName": "HRMatches"
            }
  delete:
    queryParameters:
      personId:
        required: true
        type: string
  put:
    body:
      application/json:
        type: object
        properties:
          person:
            required: true
            type: object
            properties:
              firstName: string
              phoneNumber: string
              infix: string
              language: string
              id: string
              emailaddress: string
              lastName: string
          token: string
        example: |
          {
            "person": {
              "firstName": "demo",
              "phoneNumber": "",
              "infix": "",
              "language": "nl_NL",
              "id": "7142d9e-b1be-41ac-bbcf-a6a1f4d31170",
              "emailaddress": "demo@hrmatches.com",
              "lastName": "HRMatches"
            },
            "token": "E4CB9DB5-6C62-6D46-AC1443222464C278"
          }
